# Generated by Django 4.2.9 on 2026-01-27 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('billing', 'Sistema de Facturación'), ('crm', 'CRM'), ('email', 'Email'), ('sms', 'SMS'), ('webhook', 'Webhook')], max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Integración',
                'verbose_name_plural': 'Integraciones',
                'db_table': 'integrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
