# Generated by Django 4.2.9 on 2026-01-27 22:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='last_sync',
        ),
        migrations.AddField(
            model_name='integration',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='config',
            field=models.JSONField(default=dict, help_text='Configuración específica de la integración (tokens, webhooks, etc.)'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp Business'), ('telegram', 'Telegram Bot'), ('email', 'Email'), ('slack', 'Slack'), ('api', 'API')], max_length=20),
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='integrations.integration')),
            ],
            options={
                'db_table': 'webhook_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'event_type'], name='webhook_log_platfor_d33248_idx'), models.Index(fields=['created_at'], name='webhook_log_created_33987a_idx')],
            },
        ),
    ]
