# Generated by Django 4.2.9 on 2026-01-27 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic')], max_length=50)),
                ('model_id', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('max_tokens', models.IntegerField(default=2048)),
                ('temperature', models.FloatField(default=0.7)),
            ],
            options={
                'verbose_name': 'Modelo de IA',
                'verbose_name_plural': 'Modelos de IA',
                'db_table': 'ai_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
