# Generated by Django 4.2.9 on 2026-01-27 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['event_type', 'created_at'], name='analytics_event_t_579f65_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['user', 'created_at'], name='analytics_user_id_587798_idx'),
        ),
    ]
